# Generated by Django 3.1.2 on 2021-04-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='userpic',
            field=models.ImageField(null=True, upload_to='userpics'),
        ),
    ]
