# Generated by Django 3.1.2 on 2021-04-07 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0002_client_userpic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('shedule', models.FileField(upload_to='shedules')),
                ('ratings', models.FileField(upload_to='ratings')),
                ('sheet', models.FileField(upload_to='sheets')),
                ('listeners', models.ManyToManyField(null=True, related_name='listeners', to='VEDA_application.Client')),
                ('moderators', models.ManyToManyField(null=True, related_name='moderators', to='VEDA_application.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('date_of_completion', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Ждет выполнения'), (1, 'Сделано')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VEDA_application.client')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[(1, 'Personal'), (2, 'System notification'), (3, 'Group tasks'), (4, 'Group post'), (5, 'Admin post')])),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.client')),
            ],
        ),
        migrations.CreateModel(
            name='Group_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VEDA_application.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VEDA_application.client')),
            ],
        ),
    ]
