# Generated by Django 3.1.2 on 2021-04-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0003_admin_post_group_group_post_notification_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='listeners', to='VEDA_application.Client'),
        ),
        migrations.AlterField(
            model_name='group',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderators', to='VEDA_application.Client'),
        ),
    ]
