# Generated by Django 3.1.2 on 2021-04-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0004_auto_20210408_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
