# Generated by Django 3.1.2 on 2021-04-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0005_auto_20210414_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VEDA_application.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group')),
            ],
        ),
    ]
