# Generated by Django 3.2.3 on 2021-05-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0007_client_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_post',
            options={'ordering': ['-date_of_create']},
        ),
        migrations.AlterModelOptions(
            name='group_post',
            options={'ordering': ['-date_of_create']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='group',
            name='shedule',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sheet',
        ),
        migrations.AlterField(
            model_name='client',
            name='userpic',
            field=models.ImageField(default='default.png', null=True, upload_to='userpics'),
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_receive', models.DateField()),
                ('value', models.CharField(blank=True, max_length=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group')),
                ('receiver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.client')),
            ],
        ),
        migrations.CreateModel(
            name='LessonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')])),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group')),
            ],
        ),
    ]
