# Generated by Django 3.2.3 on 2021-05-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0008_auto_20210513_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonModel',
            new_name='Lesson',
        ),
        migrations.RenameModel(
            old_name='NoteModel',
            new_name='Note',
        ),
    ]
