# Generated by Django 3.2.3 on 2021-05-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0010_group_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='discipline',
            field=models.CharField(default='Veda', max_length=40),
            preserve_default=False,
        ),
    ]
