# Generated by Django 3.2.3 on 2021-05-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0012_alter_lesson_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group'),
        ),
    ]
