# Generated by Django 3.2.3 on 2021-05-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0013_alter_lesson_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_post',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
