# Generated by Django 3.2.3 on 2021-05-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0016_auto_20210515_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.group'),
        ),
        migrations.AlterField(
            model_name='note',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VEDA_application.client'),
        ),
    ]
