# Generated by Django 3.2.3 on 2021-05-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0018_auto_20210515_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_of_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
