# Generated by Django 3.2.3 on 2021-05-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0019_alter_task_date_of_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='client',
            name='instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='vk',
            field=models.TextField(blank=True),
        ),
    ]
