# Generated by Django 3.2.3 on 2021-05-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEDA_application', '0021_note_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterField(
            model_name='parent',
            name='date_of_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='job',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
